version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: development
    reviewers:
      - divine-craft/senior-developer
    labels:
      - dependencies
      - automatic

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: development
    reviewers:
      - divine-craft/senior-developer
    labels:
      - dependencies
      - automatic
