pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - base=development
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
