language: java

before_deploy: ./.travis/scripts/import_code_signing_keys.sh

deploy:
  # Deploy snapshot to Sonatype OSSRH
  - provider: script
    edge: true
    script: ./.travis/scripts/maven_deploy.sh
    on:
      branch: development
      condition: "\"$(./.travis/scripts/get_version.sh)\" == *-SNAPSHOT"

  # Deploy release to Maven Central
  - provider: script
    edge: true
    script: ./.travis/scripts/maven_deploy.sh release
    on:
      branch: master
      tags: true
      condition: "\"$(./.travis/scripts/get_version.sh)\" != *-SNAPSHOT"

cache:
  directories:
    - ~/.m2/repository
